blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/christianulson/krnlai-communilty/discussions
    about: Please ask questions and discuss ideas here
  - name: Discord Community
    url: https://discord.gg/krnlai
    about: Join our community Discord server
